# Generated by Django 5.0.3 on 2024-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicard',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
